In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
float_data = pd.Series([1.2, -3.5, np.nan, 0])

In [4]:
float_data

0    1.2
1   -3.5
2    NaN
3    0.0
dtype: float64

In [5]:
float_data.isna()

0    False
1    False
2     True
3    False
dtype: bool

In [6]:
string_data = pd.Series(["aardvark", np.nan, None, "avocado"])

In [7]:
string_data

0    aardvark
1         NaN
2         NaN
3     avocado
dtype: str

In [8]:
string_data.isna()

0    False
1     True
2     True
3    False
dtype: bool

In [9]:
float_data = pd.Series([1,2, None] , dtype = 'float64')

In [10]:
float_data

0    1.0
1    2.0
2    NaN
dtype: float64

In [11]:
float_data.dtype

dtype('float64')

In [12]:
float_data.isna()

0    False
1    False
2     True
dtype: bool

In [13]:
data = pd.Series([1, np.nan, 3.5, np.nan, 7])

In [14]:
data.dropna()

0    1.0
2    3.5
4    7.0
dtype: float64

In [15]:
#second method to same thing is :
data[data.notna()]

0    1.0
2    3.5
4    7.0
dtype: float64

In [16]:
#these were for series methods

In [17]:
#NOW FOR DATAFRAME

In [18]:
data = pd.DataFrame([[1., 6.5, 3.], [1., np.nan, np.nan],
   ....:                      [np.nan, np.nan, np.nan], [np.nan, 6.5, 3.]])

In [19]:
data

     0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [20]:
data.dropna()

     0    1    2
0  1.0  6.5  3.0

In [21]:
data.dropna(how = "all") #Passing how="all" will drop only rows that are all NA:

     0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
3  NaN  6.5  3.0

In [22]:
# #these functions return new objects by default and do not modify
# the contents of the original object.

In [23]:
data[4] = np.nan

In [24]:
data

     0    1    2   4
0  1.0  6.5  3.0 NaN
1  1.0  NaN  NaN NaN
2  NaN  NaN  NaN NaN
3  NaN  6.5  3.0 NaN

In [25]:
data.dropna(axis = "columns", how = "all")

     0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [26]:
df = pd.DataFrame(np.random.standard_normal((7,3)))

In [27]:
df

          0         1         2
0  2.287287  0.356764 -0.077464
1 -0.471408 -0.960274 -0.473436
2 -0.932750 -0.092673 -0.347303
3 -0.573627  0.738560 -0.586138
4  2.044564  1.578502 -0.352080
5  0.531592 -0.301045  0.093911
6  1.997248 -2.513785  0.247633

In [28]:
df.iloc[:4,1] = np.nan

In [29]:
df

          0         1         2
0  2.287287       NaN -0.077464
1 -0.471408       NaN -0.473436
2 -0.932750       NaN -0.347303
3 -0.573627       NaN -0.586138
4  2.044564  1.578502 -0.352080
5  0.531592 -0.301045  0.093911
6  1.997248 -2.513785  0.247633

In [30]:
df.iloc[:6,2] = np.nan

In [31]:
df

          0         1         2
0  2.287287       NaN       NaN
1 -0.471408       NaN       NaN
2 -0.932750       NaN       NaN
3 -0.573627       NaN       NaN
4  2.044564  1.578502       NaN
5  0.531592 -0.301045       NaN
6  1.997248 -2.513785  0.247633

In [32]:
df.dropna()

          0         1         2
6  1.997248 -2.513785  0.247633

In [33]:
df.dropna(thresh = 2)

          0         1         2
4  2.044564  1.578502       NaN
5  0.531592 -0.301045       NaN
6  1.997248 -2.513785  0.247633

In [34]:
df.fillna(0)

          0         1         2
0  2.287287  0.000000  0.000000
1 -0.471408  0.000000  0.000000
2 -0.932750  0.000000  0.000000
3 -0.573627  0.000000  0.000000
4  2.044564  1.578502  0.000000
5  0.531592 -0.301045  0.000000
6  1.997248 -2.513785  0.247633

In [35]:
df.fillna({1: 0.5, 2: 0})

          0         1         2
0  2.287287  0.500000  0.000000
1 -0.471408  0.500000  0.000000
2 -0.932750  0.500000  0.000000
3 -0.573627  0.500000  0.000000
4  2.044564  1.578502  0.000000
5  0.531592 -0.301045  0.000000
6  1.997248 -2.513785  0.247633

In [36]:
df = pd.DataFrame(np.random.standard_normal((6,3)))

In [37]:
df

          0         1         2
0 -0.380757 -0.562529  0.827448
1  0.777844 -0.478411  0.424030
2  0.173225 -1.420216 -1.827402
3  0.612265 -0.982981 -1.299676
4 -0.062153  0.156553  0.389273
5  0.691972  0.637667  1.374168

In [38]:
df.iloc[2:,1] = np.nan  #PYTHON KA NAN IS PANDA KA NA

In [39]:
df

          0         1         2
0 -0.380757 -0.562529  0.827448
1  0.777844 -0.478411  0.424030
2  0.173225       NaN -1.827402
3  0.612265       NaN -1.299676
4 -0.062153       NaN  0.389273
5  0.691972       NaN  1.374168

In [40]:
df.iloc[3:,2] = np.nan

In [41]:
df

          0         1         2
0 -0.380757 -0.562529  0.827448
1  0.777844 -0.478411  0.424030
2  0.173225       NaN -1.827402
3  0.612265       NaN       NaN
4 -0.062153       NaN       NaN
5  0.691972       NaN       NaN

In [42]:
# df.fillna(method="ffill")  REMOVED FROM PANDAS
df.ffill()

          0         1         2
0 -0.380757 -0.562529  0.827448
1  0.777844 -0.478411  0.424030
2  0.173225 -0.478411 -1.827402
3  0.612265 -0.478411 -1.827402
4 -0.062153 -0.478411 -1.827402
5  0.691972 -0.478411 -1.827402

In [43]:
df.ffill(limit=2)

          0         1         2
0 -0.380757 -0.562529  0.827448
1  0.777844 -0.478411  0.424030
2  0.173225 -0.478411 -1.827402
3  0.612265 -0.478411 -1.827402
4 -0.062153       NaN -1.827402
5  0.691972       NaN       NaN

In [44]:
data = pd.Series([1., np.nan, 4., 6., np.nan])

In [45]:
data

0    1.0
1    NaN
2    4.0
3    6.0
4    NaN
dtype: float64

In [46]:
data.fillna(data.mean())

0    1.000000
1    3.666667
2    4.000000
3    6.000000
4    3.666667
dtype: float64

In [47]:
data.mean()

np.float64(3.6666666666666665)

## DATA TRANSFORMATION

#Removing Duplicates

In [48]:
data = pd.DataFrame({"k1": ["one", "two"] * 3 + ["two"],
   ....:                      "k2": [1, 1, 2, 3, 3, 4, 4]})

In [49]:
data

    k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4
6  two   4

In [50]:
data.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6     True
dtype: bool

In [51]:
# #duplicated() returns a Boolean Series indicating whether
# each row is a duplicate (its column values are exactly equal to those in an earlier row)
# or not

In [52]:
data.drop_duplicates()
#drop_duplicates returns a DataFrame with rows where the duplicated
# array is False filtered out

    k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4

In [53]:
data["v1"] = range(7)

In [54]:
data

    k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
5  two   4   5
6  two   4   6

In [55]:
data.drop_duplicates(subset=["k1"])

    k1  k2  v1
0  one   1   0
1  two   1   1

In [56]:
data.drop_duplicates(["k1", "k2"], keep="last")

    k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
6  two   4   6

#Transforming Data Using a function or mapping

In [57]:
data = pd.DataFrame({"food": ["bacon", "pulled pork", "bacon",                          
"pastrami", "corned beef", "bacon","pastrami","honey ham", "nova lox"], "ounces" : [4,3,12,6,7.5,8,3,5,6]})

In [58]:
data

          food  ounces
0        bacon     4.0
1  pulled pork     3.0
2        bacon    12.0
3     pastrami     6.0
4  corned beef     7.5
5        bacon     8.0
6     pastrami     3.0
7    honey ham     5.0
8     nova lox     6.0

In [59]:
meat_to_animal = {
"bacon": "pig",
"pulled pork": "pig",
"pastrami": "cow",
"corned beef": "cow",
"honey ham": "pig",
"nova lox": "salmon"
}

In [60]:
data["animal"] = data["food"].map(meat_to_animal)

In [61]:
data

          food  ounces  animal
0        bacon     4.0     pig
1  pulled pork     3.0     pig
2        bacon    12.0     pig
3     pastrami     6.0     cow
4  corned beef     7.5     cow
5        bacon     8.0     pig
6     pastrami     3.0     cow
7    honey ham     5.0     pig
8     nova lox     6.0  salmon

In [62]:
 def get_animal(x):
   ....:     return meat_to_animal[x]

In [63]:
data["food"].map(get_animal)

0       pig
1       pig
2       pig
3       cow
4       cow
5       pig
6       cow
7       pig
8    salmon
Name: food, dtype: str

#Replacing Values

In [64]:
 data = pd.Series([1., -999., 2., -999., -1000., 3.])

In [65]:
data

0       1.0
1    -999.0
2       2.0
3    -999.0
4   -1000.0
5       3.0
dtype: float64

In [66]:
data.replace(-999, np.nan)

0       1.0
1       NaN
2       2.0
3       NaN
4   -1000.0
5       3.0
dtype: float64

In [67]:
data.replace([-999, -1000], [np.nan, 0])

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

In [68]:
data.replace({-999: np.nan, -1000: 0})

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

#Renaming Axis Indexes

In [69]:
data = pd.DataFrame(np.arange(12).reshape((3, 4)),
....:                     
index=["Ohio", "Colorado", "New York"],
....:                     
columns=["one", "two", "three", "four"])

In [70]:
data

          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
New York    8    9     10    11

In [71]:
def transform(x):
    return x[:4].upper()

In [72]:
data.index.map(transform)

Index(['OHIO', 'COLO', 'NEW '], dtype='str')

In [73]:
# map() = replace values using a dictionary/function|

In [74]:
data.index= data.index.map(transform)

In [75]:
data

      one  two  three  four
OHIO    0    1      2     3
COLO    4    5      6     7
NEW     8    9     10    11

In [76]:
data.rename(index=str.title, columns=str.upper)

      ONE  TWO  THREE  FOUR
Ohio    0    1      2     3
Colo    4    5      6     7
New     8    9     10    11

In [77]:
 data.rename(index={"OHIO": "INDIANA"}, columns={"three": "peekaboo"})

         one  two  peekaboo  four
INDIANA    0    1         2     3
COLO       4    5         6     7
NEW        8    9        10    11

In [78]:
# #rename saves you from the chore of copying the DataFrame manually and assigning
# new values to its index and columns attributes

#Discretization and Binning

In [79]:
ages = [20, 22, 25, 27, 21, 23, 37, 31, 61, 45, 41, 32]

In [80]:
bins = [18, 25, 35,60 , 100]

In [81]:
age_categories = pd.cut(ages,bins)

In [82]:
age_categories

[(18, 25], (18, 25], (18, 25], (25, 35], (18, 25], ..., (25, 35], (60, 100], (35, 60], (35, 60], (25, 35]]
Length: 12
Categories (4, interval[int64, right]): [(18, 25] < (25, 35] < (35, 60] < (60, 100]]

In [83]:
age_categories.codes

array([0, 0, 0, 1, 0, 0, 2, 1, 3, 2, 2, 1], dtype=int8)

In [84]:
age_categories.categories

IntervalIndex([(18, 25], (25, 35], (35, 60], (60, 100]], dtype='interval[int64, right]')

In [85]:
age_categories.categories[0]

Interval(18, 25, closed='right')

In [86]:
pd.cut(ages, bins, right=False)

[[18, 25), [18, 25), [25, 35), [25, 35), [18, 25), ..., [25, 35), [60, 100), [35, 60), [35, 60), [25, 35)]
Length: 12
Categories (4, interval[int64, left]): [[18, 25) < [25, 35) < [35, 60) < [60, 100)]

In [87]:
pd.cut(ages, bins, right=True)

[(18, 25], (18, 25], (18, 25], (25, 35], (18, 25], ..., (25, 35], (60, 100], (35, 60], (35, 60], (25, 35]]
Length: 12
Categories (4, interval[int64, right]): [(18, 25] < (25, 35] < (35, 60] < (60, 100]]

In [88]:
 group_names = ["Youth", "YoungAdult", "MiddleAged", "Senior"]

In [89]:
pd.cut(ages, bins, labels = group_names)

['Youth', 'Youth', 'Youth', 'YoungAdult', 'Youth', ..., 'YoungAdult', 'Senior', 'MiddleAged', 'MiddleAged', 'YoungAdult']
Length: 12
Categories (4, str): ['Youth' < 'YoungAdult' < 'MiddleAged' < 'Senior']

In [90]:
data = np.random.uniform(size = 20)

In [91]:
data

array([0.34364139, 0.37306343, 0.81264411, 0.47851806, 0.2571867 ,
       0.18887464, 0.54318625, 0.28825796, 0.13453326, 0.0389397 ,
       0.31976368, 0.70122619, 0.29172501, 0.5491169 , 0.79292517,
       0.68639748, 0.21226086, 0.52246021, 0.70556534, 0.93367173])

In [92]:
 pd.cut(data, 4, precision=2)

[(0.26, 0.49], (0.26, 0.49], (0.71, 0.93], (0.26, 0.49], (0.038, 0.26], ..., (0.49, 0.71], (0.038, 0.26], (0.49, 0.71], (0.49, 0.71], (0.71, 0.93]]
Length: 20
Categories (4, interval[float64, right]): [(0.038, 0.26] < (0.26, 0.49] < (0.49, 0.71] < (0.71, 0.93]]

In [93]:
data = np.random.standard_normal(1000)

In [94]:
data

array([-9.79964895e-01,  1.24455520e+00,  5.51231108e-01,  8.32262675e-02,
        2.67147502e-01, -1.01594724e+00, -1.58008397e-01,  8.94722061e-01,
        3.04087352e-02, -8.18448002e-01, -2.21565090e+00, -5.99863809e-01,
        3.69367342e-01, -2.67094393e-01,  7.26053157e-01, -2.38313573e+00,
       -2.19453863e+00, -2.30150564e-01,  3.17920382e-01,  4.10415493e-02,
        9.01790572e-01,  7.60610413e-01, -2.08302652e-02, -2.71645540e+00,
       -8.17793216e-01,  1.03245048e+00,  1.30922356e+00,  1.89773552e+00,
        7.36768911e-01, -2.12276524e-01, -2.69918130e+00, -1.14831574e+00,
        5.07700293e-01, -4.99912877e-01,  4.36260624e-01, -1.15302414e+00,
        7.45522731e-01, -2.29600463e-01,  2.04945318e-01, -5.39856653e-01,
       -5.06754868e-02, -9.29298664e-01, -6.31636431e-03,  1.65035929e-02,
        1.14489752e+00, -1.66582876e+00,  1.70982842e+00,  1.07818481e-02,
       -5.00756735e-01, -3.87390280e-02,  1.19987848e-01,  1.41092156e+00,
        7.58741192e-01, -1.13756830e+00,  4.30956275e-01, -2.94783250e-01,
       -6.10398621e-01, -1.24807479e+00, -1.37034730e+00,  4.71877625e-01,
        5.69935677e-01, -1.38655732e+00, -2.97915599e-01, -1.74201334e+00,
        3.99465734e-01,  1.69223286e-01, -1.24087110e+00, -1.65749551e-01,
        8.47692906e-02,  1.16734439e+00,  1.02539473e+00, -1.25185738e-01,
       -8.01068767e-01, -1.20042815e+00, -4.87270644e-01,  4.57571773e-02,
        6.33542050e-01,  1.06035039e+00,  7.02137770e-01,  4.28030675e-01,
        6.98536304e-02,  1.14726002e+00,  6.85513690e-01, -1.43803674e+00,
        1.31048889e+00,  3.35173263e-02,  1.14745173e+00,  7.81130981e-01,
        6.12829354e-01, -5.77414166e-01,  1.36222701e+00, -1.56752032e+00,
        6.81494246e-02,  9.38416212e-01,  2.25311063e-01,  1.13153227e+00,
        1.25111612e-01, -6.41525811e-02, -2.27429879e+00, -1.47256495e-01,
        7.14273626e-02, -9.58809081e-01,  1.28286974e+00, -4.39681025e-01,
       -4.71268079e-01,  2.89603838e-01, -1.82215341e+00, -9.29003690e-02,
       -1.16788622e+00, -1.05366596e+00,  7.09275927e-01, -3.76100503e-01,
        5.70100681e-01,  6.42775404e-01,  2.19709416e-01,  1.13058459e-01,
       -3.12670009e-01,  3.66650735e-01, -8.01513732e-01, -4.25071996e-02,
        7.65096244e-02,  1.00454022e+00,  2.83652304e-01, -1.12171487e+00,
        3.51786545e-01,  1.22195074e-01,  2.52220861e-01, -7.85751402e-01,
       -2.92279519e-01,  9.98480812e-01,  1.59633418e+00,  9.63758815e-01,
        1.07405701e+00, -4.18658217e-01,  1.08216115e+00,  7.46025106e-01,
        4.19469167e-01,  8.50034030e-01,  2.14110855e-01,  7.72301156e-01,
        6.00730544e-01, -5.61932875e-01, -1.13263143e-01, -8.31245314e-01,
       -9.66663772e-01,  1.81564295e-01,  1.14603728e-01, -9.34391277e-01,
        1.69268112e-01, -1.23226105e+00, -1.77290395e+00,  8.73191103e-01,
        4.61713969e-01,  5.68766085e-01, -5.76271687e-01, -8.32588552e-01,
       -1.64115023e+00,  9.64274727e-01,  2.93026549e-01, -1.05742478e+00,
        2.76324530e-01, -6.02451274e-01, -6.41834544e-01, -1.87367784e-01,
       -2.61267098e-01,  4.75846995e-01,  1.10393331e+00,  1.47032813e-01,
       -2.65394123e-01,  1.42907758e-01, -2.12718156e-01,  3.29779034e-01,
        6.43727202e-01, -3.07274429e-01,  8.85112369e-01, -2.16355147e-01,
        7.69089131e-01, -1.53121769e+00, -1.29974994e+00, -1.53445591e+00,
        9.80457959e-01,  7.96700435e-01, -2.56807086e-01,  2.78868326e-01,
       -7.90783749e-01, -1.87913883e+00,  6.99359314e-01,  9.91107282e-01,
       -8.50198177e-01, -1.23839845e-01,  1.31460225e+00, -6.02575785e-01,
        4.85593918e-01, -6.47324783e-01,  9.99320736e-01,  1.30601663e+00,
        5.50311610e-01, -1.58960281e-01,  5.65054717e-02,  4.28877612e-02,
       -4.35326035e-01,  1.72286814e+00, -4.69768407e-01, -2.74960698e-01,
       -9.39939087e-01, -1.04316488e+00,  3.41023981e-01,  1.05317704e+00,
       -3.50176472e-01, -1.02134417e+00, -4.51279149e-01,  1.72004103e+00,
       -1.27926450e+00, -8.21173305e-01,  1.65611477e-01,  3.70574951e-01,
       -2.29787559e-01, -5.30169368e-01,  8.89007290e-01,  2.58642746e+00,
       -1.37553477e+00, -6.28980862e-01,  4.89280132e-02, -4.46849234e-01,
       -2.63088324e-01, -1.63813372e+00,  9.08324629e-01, -6.56457205e-01,
       -1.71648530e+00,  6.81309101e-01, -6.19553521e-01,  1.26851030e+00,
       -4.62525046e-01, -5.96367449e-01,  2.03043750e+00, -4.60704471e-01,
       -1.18890597e-01, -8.73773333e-01, -1.25341917e+00, -6.50368248e-01,
       -1.34884155e+00, -9.10145242e-01,  8.08332326e-02,  1.18295960e+00,
       -1.43442550e+00,  1.51711494e-01, -1.14103605e+00, -6.26172836e-01,
       -5.84061369e-01,  1.01473875e+00, -4.00826417e-01,  8.83833505e-02,
        1.89566820e+00, -1.31421453e+00,  2.08822376e+00, -1.30906111e+00,
        3.38599132e-01, -5.82384625e-01, -4.04171011e-01,  1.61783538e-01,
        4.55465425e-01, -3.02465752e-01,  3.20248215e-01, -3.63423992e-02,
       -1.22406264e-01,  9.34537190e-01, -6.09195982e-01,  1.71390090e-02,
       -8.15640513e-01,  3.49622935e-01, -5.50632755e-01, -1.30725038e+00,
        4.30139570e-01,  6.01110301e-01, -3.16322877e-01, -1.36851336e-01,
        8.02548140e-01, -4.84672879e-01, -4.79448473e-01, -2.98308180e-01,
       -2.01796437e-01,  1.69836518e-01, -8.40154611e-01, -1.59307773e+00,
       -8.35978013e-01,  1.30039663e+00,  1.40151740e+00, -7.91452961e-01,
        8.29357811e-01,  3.71801486e-01, -1.96720220e-01, -4.16046328e-01,
        1.09462422e+00, -1.80823526e+00, -1.85003793e+00,  3.25775971e-01,
        4.19884118e-01,  2.48338666e-01, -3.33716670e-01, -2.76094383e+00,
        1.69774295e+00, -3.67236152e-01, -9.85802275e-01,  2.78594137e-01,
       -8.57052874e-01,  2.40958009e-01,  2.14637492e-01,  5.81636977e-01,
       -1.72912624e+00, -1.97814158e+00,  7.70162264e-01, -5.42398090e-01,
       -3.90782290e-01,  5.90322121e-01, -1.65753447e+00, -6.74921103e-01,
       -1.73848257e-01,  4.73219230e-02, -8.23287140e-01,  6.76983901e-02,
       -8.63424668e-01,  7.21040097e-01, -6.86695760e-01,  3.62393634e-01,
        3.41159542e-01,  4.46174547e-01, -4.86036794e-01,  8.46807106e-01,
       -1.10715548e+00, -5.15641871e-01,  3.14263932e-01, -1.70054518e+00,
       -8.43426645e-01, -6.53927085e-01,  1.40765192e+00,  1.47189561e-01,
       -6.67561704e-01, -2.91824720e-01, -9.71632133e-01,  3.07348903e-01,
       -1.26011703e+00, -4.92272665e-01, -1.96826753e+00, -6.59570497e-02,
        8.90472633e-01, -4.39624151e-01, -7.92236506e-01,  1.62790231e+00,
        6.19541158e-01,  3.72533666e+00,  1.94617183e+00,  5.31939172e-01,
       -5.12115749e-01, -1.51543777e+00,  2.04814388e+00,  5.39958834e-01,
       -2.98955251e-01,  1.48597531e+00, -3.31685209e-01, -1.55230726e+00,
       -9.76555250e-01, -3.07283669e-03,  8.53445470e-01, -8.87296621e-02,
        1.40529028e+00,  1.29742755e+00,  7.67064657e-01, -9.61330803e-01,
       -6.96672489e-01, -5.91794128e-02,  9.25150520e-01, -1.53679631e+00,
        5.36992067e-01, -6.13083169e-01,  3.18122950e-02, -9.05454505e-01,
       -6.35226042e-01, -7.97875882e-01, -3.97615043e-01,  4.90938277e-01,
       -1.28881104e-01,  2.66196332e+00,  4.83427775e-01,  1.57953280e-01,
        3.50223005e-01, -4.06530564e-01,  6.76839032e-01, -5.56050550e-02,
       -8.57197934e-02,  2.46324060e-01,  8.10905589e-01, -1.98842827e-01,
        1.18984935e+00,  1.21420033e+00,  6.21182815e-02, -2.26062672e+00,
        7.21192864e-01,  5.14720867e-01, -1.27073466e+00, -9.70459209e-01,
        8.80810883e-02,  2.99980312e-01, -5.36725884e-01,  2.81760541e+00,
       -5.63507504e-01, -4.05982675e-01,  7.40822815e-02,  9.52090422e-01,
       -9.94606029e-01,  1.77202929e-01, -4.24029805e-01, -8.54452751e-03,
        1.11259083e+00, -2.43961818e-01, -1.74540457e+00,  1.16577828e-01,
       -1.38190917e-01,  8.01479402e-01, -1.02884007e+00,  1.13516964e-02,
       -1.17469801e+00, -2.18004816e-01,  7.71416651e-01,  1.45530318e+00,
        5.39739034e-01, -5.12942846e-01, -2.51235090e-01, -2.77825591e-01,
        1.60801564e-01,  4.41717735e-01, -1.13942045e+00,  5.87663104e-01,
       -8.70845990e-01,  8.24683703e-01, -1.51407682e+00, -7.12651395e-01,
       -4.54408867e-01,  1.45059497e+00,  4.79432012e-01, -3.15359183e-01,
        5.89405775e-01, -2.42656133e+00,  1.81464445e+00, -8.66108593e-01,
        1.10948614e+00, -7.95605001e-01,  4.98027851e-02,  3.68332936e-01,
       -1.33980480e+00, -5.17777895e-01, -9.99526817e-01,  5.83629759e-01,
        1.30750174e+00,  4.84154923e-01, -8.23509007e-02, -6.80291165e-01,
        5.56828745e-01,  7.57956455e-01, -3.86547132e-01,  9.21407253e-01,
        6.12065424e-01, -1.53232155e+00,  5.95915999e-01,  7.77841324e-01,
       -6.68760098e-01, -1.88781233e-02, -1.49684354e+00,  6.17477619e-01,
       -1.59817596e+00, -4.45145856e-02, -1.28279257e+00, -2.09200855e+00,
        1.37431328e+00, -6.61314323e-01, -1.61069802e+00, -4.23767942e-02,
       -6.90871351e-01, -1.16176976e+00,  1.01759041e+00, -1.75667873e+00,
        1.21507110e+00,  2.18016183e-01,  1.01485432e+00,  3.07859312e-01,
        2.12147519e-01,  1.50897978e+00, -5.54877508e-02, -8.30237347e-01,
        8.71750851e-01, -1.88270659e-01,  1.78870049e-01, -1.51449169e+00,
        1.56845249e-01, -4.22721883e-01, -3.15625873e-01, -9.99442936e-01,
        1.81693961e+00, -1.07329060e+00, -2.54658305e-01, -1.04297530e+00,
        1.35941011e-01,  1.18501480e+00, -1.14684496e+00, -5.78954166e-01,
       -1.34050112e+00,  6.95184269e-01, -1.93005429e-01, -7.33396052e-01,
        5.06908429e-01, -2.33864107e+00, -4.75663139e-03, -5.14462380e-01,
        5.20961426e-01, -7.86098720e-02,  1.15999789e-01,  1.38515326e+00,
       -1.13697815e+00,  1.26836950e-01, -1.28171536e+00,  2.39773322e-01,
        2.12793809e-01,  5.74772168e-01,  5.67764504e-01, -7.40357888e-01,
       -1.12730712e+00,  2.47257578e-01,  4.04251438e-01,  2.87552758e-01,
        1.06916877e+00, -1.19246327e+00, -2.64192064e+00,  6.11579944e-02,
        5.54117830e-01, -2.34451388e-01, -8.25575603e-01, -3.14107315e-01,
        7.20057261e-01,  6.67534062e-01, -3.89420996e-01,  7.82940454e-01,
       -1.41726439e+00, -3.09904271e-01,  8.63578501e-01, -7.66747277e-01,
       -1.31057344e+00,  1.47382474e+00,  9.14514665e-01,  2.32951010e+00,
       -5.48485037e-01,  1.72959967e-01, -7.39942658e-01, -3.33139759e-01,
        1.15742886e+00,  1.67361042e-01,  7.10506394e-01, -1.20260053e+00,
       -3.45924207e-01, -2.31893060e-01, -2.76853205e-01,  4.64452339e-01,
        3.36491415e-01, -1.74438526e+00,  6.41194903e-01,  1.82928600e+00,
       -1.47511864e+00, -1.06274985e+00, -9.24141646e-01,  2.01880229e+00,
        6.61444719e-01, -2.03207917e-01, -2.42588163e-02, -9.95837204e-03,
       -3.92265378e-01,  1.91437067e+00,  1.65491143e+00,  1.10358636e+00,
       -1.59086600e-01,  6.43073344e-01, -2.21873755e+00,  9.21312104e-01,
       -2.26995315e-01, -8.22336790e-01, -1.79871336e+00, -3.42786601e-01,
       -2.10501440e+00,  3.34759897e-01,  8.43403474e-02,  2.76136414e-02,
        1.39263613e+00, -1.01377614e+00,  1.95076577e+00,  7.32954801e-01,
        1.23264582e+00,  5.48997273e-01, -4.95779654e-01,  4.81133915e-01,
       -1.29187403e+00,  5.13719266e-01, -8.91544171e-01, -4.77277427e-01,
        8.65499432e-01,  1.18668426e+00,  5.38735465e-01, -4.20911925e-01,
       -3.47942477e-01,  8.78805966e-01,  1.94519512e+00,  1.66968538e+00,
        5.36266177e-01, -1.19056649e-01,  8.14317958e-01,  7.41056761e-01,
       -9.57740470e-01, -3.72411084e-01,  2.01725019e+00, -6.57143775e-03,
        1.91030374e+00,  1.89178049e+00, -1.99663678e-01, -5.71898580e-01,
       -1.42314063e+00,  5.55200359e-01,  1.19250268e+00, -3.15874435e-01,
       -9.78083352e-01,  1.70294694e+00,  1.18653283e-02, -1.07222563e+00,
        6.00567234e-01,  1.43602250e+00,  6.34078056e-01, -3.81146349e-01,
        8.19644504e-02,  1.29724920e-01, -1.30914613e+00, -4.01139517e-01,
        4.80882109e-01,  5.88601927e-02,  1.17561047e+00, -1.28513373e+00,
        7.31147678e-01, -1.73660355e+00, -5.44270140e-01,  5.43516758e-01,
        8.28259182e-01,  2.33824679e-01,  7.04759046e-02,  5.84363016e-01,
        8.90009253e-01,  2.55574107e-02, -8.96558566e-01, -1.34576339e+00,
        3.97304389e-01,  4.44385103e-01, -6.77999935e-01, -1.51272973e+00,
       -2.22860381e-02, -5.71707491e-01,  1.17717337e+00,  1.70012982e+00,
        8.95932628e-01, -6.29001646e-01, -3.37856565e-01,  1.93040810e+00,
       -1.68646469e-01, -7.92639263e-01,  1.48881095e+00, -1.93714245e+00,
        3.35435362e-01, -1.16492252e+00, -1.92540233e-01,  6.48174844e-01,
       -9.72325169e-01,  1.91551145e+00,  2.06925798e+00, -1.27523842e-01,
       -1.47400980e-01,  2.92634219e-01,  1.36287038e+00,  3.11096406e-01,
       -1.50980479e+00,  4.40343840e-02, -6.19420443e-01, -4.67343720e-01,
        1.43122403e+00,  9.12565112e-01,  5.00737940e-02, -5.93038276e-01,
       -1.84328355e+00,  5.36713146e-01, -2.02578957e+00,  1.65815526e-01,
        2.26299366e+00,  9.22771728e-01,  3.00875439e-01, -1.00904880e+00,
       -4.03447060e-02,  1.03706882e+00, -3.24775313e-01, -4.31156285e-01,
       -6.77082643e-01,  9.59252753e-02, -2.09372080e+00, -5.82541665e-01,
       -2.29260562e-01, -7.54293369e-01,  4.83157046e-01, -1.15392417e+00,
       -4.43884302e-01, -9.28425548e-01, -2.60099485e-01, -1.82171721e-01,
        7.84406195e-01, -7.28782735e-01,  7.03257788e-01,  9.13626403e-01,
        3.51238354e-01, -2.21922737e+00, -9.01342324e-01,  7.56091071e-01,
        2.52797122e-01,  3.17824522e-01,  5.25810974e-01,  4.45780246e-01,
        2.51254744e-01,  8.40276879e-01, -6.31358995e-01,  1.19426104e+00,
       -6.94578351e-01, -1.00748706e+00,  4.91540094e-01, -8.88778080e-01,
       -1.50816350e+00,  1.65095954e+00,  8.44899159e-01,  8.56741157e-01,
        8.89694701e-01,  2.74297072e-01, -1.23405088e+00,  6.42500969e-01,
       -8.70815888e-01, -8.86914204e-01, -9.86762346e-01, -9.35548266e-01,
       -2.91881556e-01, -6.43219276e-01,  3.34259528e-03, -2.07372226e+00,
       -8.95591567e-02, -1.28730379e-01,  1.15218617e+00,  8.70715778e-01,
       -1.39480903e+00,  1.83108318e+00,  1.42923489e-01,  1.05515999e+00,
       -6.19836811e-01,  1.73091928e-01, -2.36535076e+00,  7.83967588e-01,
       -4.03738740e-01, -3.47314154e-01, -8.87643217e-01, -4.09080072e-01,
        1.27918170e+00,  8.07785263e-01, -6.57363911e-01, -1.42105123e+00,
        8.08296939e-03, -5.83799267e-01, -1.37891347e-02,  6.98591711e-01,
        6.79523472e-01, -7.21780360e-01,  1.66610140e+00,  1.53395926e+00,
       -9.40483327e-01, -3.85475447e+00,  5.05301265e-01, -9.69812100e-01,
       -4.42646911e-01, -2.89982439e-02,  2.27643847e-02, -1.80554035e-01,
        7.45420321e-01, -1.43712745e+00, -2.08119998e+00, -7.04154163e-01,
       -5.99178252e-01, -2.52775253e+00, -1.95558936e+00,  1.52322294e+00,
       -6.49978258e-01, -1.14255323e+00,  2.99069233e-01,  1.29794508e+00,
       -5.35022675e-02, -2.42292830e-01, -5.97191554e-01, -5.63010290e-01,
        3.42930804e-01,  6.94686605e-01, -2.06330424e+00,  1.11466916e+00,
        1.07300969e+00, -3.17604195e-01,  6.70749370e-01,  1.58155873e+00,
       -1.24905809e+00,  1.79292521e+00,  2.07348657e+00, -4.74303232e-01,
        4.36128532e-01, -1.00579051e+00, -5.63222306e-01, -8.23073606e-01,
        1.05152539e+00,  1.65052276e+00, -2.96810655e-01, -8.71247427e-01,
        1.84155804e-01,  3.81425525e-01,  5.70545779e-01,  1.07948974e+00,
       -1.04629383e+00, -1.08933551e+00,  3.32137320e-01, -1.34706543e+00,
       -8.27442821e-01, -5.13958427e-02, -9.68562832e-01,  6.05362874e-01,
       -3.32063679e-01,  1.67143357e+00,  6.21107074e-01, -5.37941506e-01,
        1.37455584e+00,  2.16436060e-01,  1.88596896e+00,  4.29685836e-01,
       -1.67165153e+00,  3.08275061e-01,  1.61297359e-01, -2.43696628e-01,
       -1.43800389e+00, -9.92011103e-01, -7.29021019e-01,  1.46447489e-01,
       -1.65165336e+00, -1.60632190e+00,  7.34352220e-02, -1.26226945e+00,
       -1.02330398e-01, -1.37279307e+00, -5.40590324e-01, -1.40682041e+00,
       -1.90677409e+00,  4.28355037e-02,  2.81030862e-01,  7.49379842e-01,
        9.11935105e-02, -1.32607029e+00, -1.02863809e+00, -5.96075492e-01,
        5.77904278e-01,  5.04863972e-01, -1.42960680e+00, -7.70595507e-01,
       -8.39016199e-01,  1.18272510e-01,  3.49466907e-01, -3.49285034e-02,
       -1.81926911e+00,  2.07789040e-01, -8.20318575e-01, -2.88531671e-01,
        1.14380731e+00,  3.60526257e-01, -1.41823688e+00,  1.04539489e+00,
        1.47244961e-01,  4.26013651e-01, -3.11506479e-01, -6.64924410e-01,
       -3.36870554e-01,  7.22670691e-01, -1.77738861e+00, -2.86690737e-02,
       -3.62689009e-01,  2.66964256e+00, -1.38024324e-01,  1.75231739e+00,
        1.85078702e-01, -1.01849614e+00,  6.84145186e-01,  2.44711793e+00,
       -1.48730766e-01, -7.43329091e-02, -2.41366246e+00, -7.24399586e-01,
       -1.49163385e+00, -1.84308795e-01,  1.11516936e+00,  2.72366050e-01,
       -2.55383997e-01,  2.86029509e+00,  1.65413392e+00, -2.56861346e-01,
       -2.39368796e-01,  6.17974513e-01, -7.84073853e-01,  5.34925564e-02,
        1.35542985e+00,  9.75938103e-01, -5.60449451e-01, -1.05921937e+00,
        1.64593650e-01, -1.17077871e+00, -1.89819298e+00,  5.36796553e-01,
       -1.10634430e+00, -2.57859275e-01, -4.43017443e-02, -7.08220307e-01,
       -1.39304552e+00,  1.26693081e-01, -5.10527272e-02,  2.14841301e+00,
        5.73642462e-01, -1.82297909e+00, -1.84831389e+00, -1.80566445e+00,
        4.31305091e-01,  2.50758580e-01, -8.10582723e-02,  1.65543891e+00,
        7.89093968e-01,  8.02307369e-01, -4.28285181e-01,  1.30572860e+00,
        3.43655170e-01,  1.88712187e-01, -3.75841272e-01, -3.78835230e-01,
        4.43810126e-01, -9.36443118e-01, -1.58107579e+00, -3.65926531e-01,
       -7.43846454e-01,  1.89980174e+00,  7.06208129e-01, -1.36052184e+00,
       -6.03353792e-01, -1.12944960e+00, -2.36452100e-01, -5.06051865e-01,
       -1.08864934e+00, -8.67321413e-01, -1.47539927e+00, -1.07958269e+00,
        1.95855654e-02,  9.60523871e-02, -1.33133544e-01, -9.09395282e-01,
       -2.78082682e-01,  7.01453232e-01, -8.72343171e-01,  1.82593557e+00,
       -1.34041092e+00, -4.85463730e-01, -1.83135561e+00,  3.29098568e-01,
       -1.17227616e+00,  6.10944336e-01, -1.51282680e-01,  1.39394800e+00,
        4.15997752e-01,  7.86015691e-01, -8.98115106e-01, -1.04343287e+00,
        2.54337773e-01,  2.70694206e+00, -1.66150585e+00,  2.80157760e-01,
        2.04767492e+00, -1.50978553e-01,  1.16732508e+00, -1.70988711e+00,
        5.46195260e-01, -5.70378881e-01,  1.88626707e-01, -1.21022851e+00,
       -1.05750414e+00,  7.55563691e-01, -5.10661627e-03, -5.86040515e-01,
       -1.65958734e+00,  1.82724497e-01,  3.93251625e-01,  2.00039016e+00])

In [95]:
quartiles = pd.qcut(data, 4, precision=2)

In [96]:
quartiles

[(-3.86, -0.74], (0.6, 3.73], (-0.043, 0.6], (-0.043, 0.6], (-0.043, 0.6], ..., (-0.74, -0.043], (-3.86, -0.74], (-0.043, 0.6], (-0.043, 0.6], (0.6, 3.73]]
Length: 1000
Categories (4, interval[float64, right]): [(-3.86, -0.74] < (-0.74, -0.043] < (-0.043, 0.6] < (0.6, 3.73]]

In [97]:
# pd.count(quartiles) REDO IT KYUNKI YEH PANDAS SE REMOVE KR DIYA GYA HAI !!

In [98]:
pd.qcut(data, [0, 0.1, 0.5, 0.9, 1.]).value_counts()

(-3.856, -1.346]     100
(-1.346, -0.0434]    400
(-0.0434, 1.178]     400
(1.178, 3.725]       100
Name: count, dtype: int64

# Detecting and Filtering Outliers

In [99]:
data = pd.DataFrame(np.random.standard_normal((1000,4)))

In [100]:
data

            0         1         2         3
0   -0.212897 -0.060719 -1.614923  1.380346
1    0.525301 -0.176962 -0.140458 -1.055940
2   -0.830090  0.262803  0.127515  1.003966
3    0.999323 -0.838531 -0.048311 -1.628016
4   -0.205463 -2.080079  0.932869 -0.465225
..        ...       ...       ...       ...
995 -1.532725 -0.590047 -0.208768  0.914519
996  0.216267  0.680848  0.394335 -0.454466
997  0.437142  1.031806  1.180285  0.541025
998  0.574865 -1.762439  0.372532 -0.187953
999  2.879165 -0.716680 -0.352594  1.149559

[1000 rows x 4 columns]

In [101]:
data.describe()

                 0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean      0.010296     0.054778    -0.026323    -0.011895
std       1.014813     1.047135     0.975607     1.026570
min      -3.108883    -3.553997    -3.593102    -3.149369
25%      -0.700471    -0.621732    -0.702934    -0.682407
50%      -0.002069     0.042256     0.032143     0.022751
75%       0.731051     0.734517     0.635348     0.691077
max       3.386747     3.827184     2.565046     4.023178

In [102]:
col = data[2]

In [103]:
 col[col.abs() > 3]

344   -3.593102
Name: 2, dtype: float64

In [104]:
data[(data.abs() > 3).any(axis="columns")]

            0         1         2         3
6    0.119480 -2.964096  0.884796  3.317599
185  0.197865 -0.262157  0.406094  4.023178
238  2.246237 -3.253652 -0.877089 -0.079226
344 -2.734788  0.427542 -3.593102  0.596495
359  3.386747 -0.471304  0.617561 -1.699915
502 -1.118505  3.827184 -1.122458 -0.603058
513 -0.169793  0.373005 -1.148074 -3.072748
540 -0.606967 -3.332711 -0.542203 -0.127698
610  0.733231 -3.553997 -0.169867 -0.478223
622  0.484912 -3.231536 -0.949528  0.268066
722  0.830934  1.444880 -0.363828 -3.029511
742  0.162421  3.071388 -1.622651 -0.979912
881 -1.814397 -0.208164 -0.162162 -3.149369
958 -3.108883  0.622121  0.968172 -0.248135

In [105]:
data[data.abs() > 3] = np.sign(data) * 3

data.describe()

In [106]:
 # np.sign(data) produces 1 and –1

In [107]:
np.sign(data).head()

     0    1    2    3
0 -1.0 -1.0 -1.0  1.0
1  1.0 -1.0 -1.0 -1.0
2 -1.0  1.0  1.0  1.0
3  1.0 -1.0 -1.0 -1.0
4 -1.0 -1.0  1.0 -1.0

# Permutation and Random Sampling

In [108]:
df = pd.DataFrame(np.arange(5*7).reshape((5,7)))

In [109]:
df

    0   1   2   3   4   5   6
0   0   1   2   3   4   5   6
1   7   8   9  10  11  12  13
2  14  15  16  17  18  19  20
3  21  22  23  24  25  26  27
4  28  29  30  31  32  33  34

In [110]:
sampler = np.random.permutation(5)

In [111]:
sampler

array([2, 4, 3, 0, 1], dtype=int32)

In [112]:
df.take(sampler)

    0   1   2   3   4   5   6
2  14  15  16  17  18  19  20
4  28  29  30  31  32  33  34
3  21  22  23  24  25  26  27
0   0   1   2   3   4   5   6
1   7   8   9  10  11  12  13

In [113]:
df.iloc[sampler]

    0   1   2   3   4   5   6
2  14  15  16  17  18  19  20
4  28  29  30  31  32  33  34
3  21  22  23  24  25  26  27
0   0   1   2   3   4   5   6
1   7   8   9  10  11  12  13

In [114]:
column_sampler = np.random.permutation(7)

In [115]:
column_sampler

array([4, 6, 2, 1, 3, 0, 5], dtype=int32)

In [116]:
df.take(column_sampler, axis="columns")

    4   6   2   1   3   0   5
0   4   6   2   1   3   0   5
1  11  13   9   8  10   7  12
2  18  20  16  15  17  14  19
3  25  27  23  22  24  21  26
4  32  34  30  29  31  28  33

In [117]:
df.sample(n = 3)

    0   1   2   3   4   5   6
4  28  29  30  31  32  33  34
2  14  15  16  17  18  19  20
0   0   1   2   3   4   5   6

In [118]:
df.sample(n=3, replace = True)

    0   1   2   3   4   5   6
2  14  15  16  17  18  19  20
1   7   8   9  10  11  12  13
2  14  15  16  17  18  19  20

In [119]:
choices = pd.Series([5, 7, -1, 6, 4])

In [120]:
choices.sample(n=10, replace=True)

4    4
3    6
1    7
3    6
0    5
2   -1
2   -1
1    7
0    5
0    5
dtype: int64

In [121]:
df = pd.DataFrame({"key": ["b", "b", "a", "c", "a", "b"], "data1": range(6)})

In [122]:
df

  key  data1
0   b      0
1   b      1
2   a      2
3   c      3
4   a      4
5   b      5

In [123]:
pd.get_dummies(df)

   data1  key_a  key_b  key_c
0      0  False   True  False
1      1  False   True  False
2      2   True  False  False
3      3  False  False   True
4      4   True  False  False
5      5  False   True  False

In [124]:
pd.get_dummies(df["key"])

       a      b      c
0  False   True  False
1  False   True  False
2   True  False  False
3  False  False   True
4   True  False  False
5  False   True  False

In [125]:
#here false = .0 and true = 1

In [126]:
dummies = pd.get_dummies(df["key"], prefix = "key")

In [127]:
df_with_dummy = df[["data1"]].join(dummies)

In [128]:
df_with_dummy

   data1  key_a  key_b  key_c
0      0  False   True  False
1      1  False   True  False
2      2   True  False  False
3      3  False  False   True
4      4   True  False  False
5      5  False   True  False

In [129]:
 mnames = ["movie_id", "title", "genres"]

In [130]:
movies = pd.DataFrame( {"movie_id" : list(range(1 ,11)), "title" : ["Toy Story (1995)","Jumanji (1995)","Grumpier Old Man(1995)", "Waiting to Exhale (1995) ", " Father of the Bride Part II (1995)","Heat(1995)"," Sabrina(1995) ","Tom and Huck (1995)  ","Sudden Death (1995)","GoldenEye (1995)"], 
                       "genres" : ["Animation|Children's|Comedy","Adventure|Children's|Fantasy","Comedy|Romance","Comedy|Drama"," Comedy","Action|Crime|Thriller","  Comedy|Romance" ,"Adventure|Children's"," Action","Action|Adventure|Thriller"]})

In [131]:
movies

   movie_id                                title                        genres
0         1                     Toy Story (1995)   Animation|Children's|Comedy
1         2                       Jumanji (1995)  Adventure|Children's|Fantasy
2         3               Grumpier Old Man(1995)                Comedy|Romance
3         4            Waiting to Exhale (1995)                   Comedy|Drama
4         5   Father of the Bride Part II (1995)                        Comedy
5         6                           Heat(1995)         Action|Crime|Thriller
6         7                       Sabrina(1995)                 Comedy|Romance
7         8                Tom and Huck (1995)            Adventure|Children's
8         9                  Sudden Death (1995)                        Action
9        10                     GoldenEye (1995)     Action|Adventure|Thriller

In [132]:
movies[:10]

   movie_id                                title                        genres
0         1                     Toy Story (1995)   Animation|Children's|Comedy
1         2                       Jumanji (1995)  Adventure|Children's|Fantasy
2         3               Grumpier Old Man(1995)                Comedy|Romance
3         4            Waiting to Exhale (1995)                   Comedy|Drama
4         5   Father of the Bride Part II (1995)                        Comedy
5         6                           Heat(1995)         Action|Crime|Thriller
6         7                       Sabrina(1995)                 Comedy|Romance
7         8                Tom and Huck (1995)            Adventure|Children's
8         9                  Sudden Death (1995)                        Action
9        10                     GoldenEye (1995)     Action|Adventure|Thriller

In [133]:
dummies = movies["genres"].str.get_dummies("|")

In [134]:
dummies.iloc[:10, :6]

     Comedy   Action   Comedy  Action  Adventure  Animation
0         0        0        0       0          0          1
1         0        0        0       0          1          0
2         0        0        0       0          0          0
3         0        0        0       0          0          0
4         0        0        1       0          0          0
5         0        0        0       1          0          0
6         1        0        0       0          0          0
7         0        0        0       0          1          0
8         0        1        0       0          0          0
9         0        0        0       1          1          0

In [135]:
 movies_windic = movies.join(dummies.add_prefix("Genre_"))

In [136]:
movies_windic.iloc[0]

movie_id                                      1
title                          Toy Story (1995)
genres              Animation|Children's|Comedy
Genre_  Comedy                                0
Genre_ Action                                 0
Genre_ Comedy                                 0
Genre_Action                                  0
Genre_Adventure                               0
Genre_Animation                               1
Genre_Children's                              1
Genre_Comedy                                  1
Genre_Crime                                   0
Genre_Drama                                   0
Genre_Fantasy                                 0
Genre_Romance                                 0
Genre_Thriller                                0
Name: 0, dtype: object

In [137]:
movies_windic.iloc[1]

movie_id                                       2
title                             Jumanji (1995)
genres              Adventure|Children's|Fantasy
Genre_  Comedy                                 0
Genre_ Action                                  0
Genre_ Comedy                                  0
Genre_Action                                   0
Genre_Adventure                                1
Genre_Animation                                0
Genre_Children's                               1
Genre_Comedy                                   0
Genre_Crime                                    0
Genre_Drama                                    0
Genre_Fantasy                                  1
Genre_Romance                                  0
Genre_Thriller                                 0
Name: 1, dtype: object

In [138]:
np.random.seed(12345)

In [139]:
values = np.random.uniform(size = 10)

In [140]:
values

array([0.92961609, 0.31637555, 0.18391881, 0.20456028, 0.56772503,
       0.5955447 , 0.96451452, 0.6531771 , 0.74890664, 0.65356987])

In [141]:
bins =  [0, 0.2, 0.4, 0.6, 0.8, 1]

In [142]:
 pd.get_dummies(pd.cut(values, bins))

   (0.0, 0.2]  (0.2, 0.4]  (0.4, 0.6]  (0.6, 0.8]  (0.8, 1.0]
0       False       False       False       False        True
1       False        True       False       False       False
2        True       False       False       False       False
3       False        True       False       False       False
4       False       False        True       False       False
5       False       False        True       False       False
6       False       False       False       False        True
7       False       False       False        True       False
8       False       False       False        True       False
9       False       False       False        True       False

In [143]:
s = pd.Series([1,2,3,None])

In [144]:
s.dtype

dtype('float64')

In [145]:
s = pd.Series([1, 2, 3, None], dtype=pd.Int64Dtype())

In [146]:
s

0       1
1       2
2       3
3    <NA>
dtype: Int64

In [147]:
s.isna()

0    False
1    False
2    False
3     True
dtype: bool

In [148]:
s.dtype

Int64Dtype()

In [149]:
s[3]

In [150]:
s[3] is pd.NA

True

In [151]:
s = pd.Series([1,2,3,None], dtype = "Int64")

In [152]:
s

0       1
1       2
2       3
3    <NA>
dtype: Int64

In [153]:
s = pd.Series(['one', 'two', None, 'three'], dtype=pd.StringDtype())

In [154]:
s

0      one
1      two
2     <NA>
3    three
dtype: string

In [155]:
s.dtype

In [156]:
s.isna()

0    False
1    False
2     True
3    False
dtype: bool

In [157]:
df = pd.DataFrame({"A": [1, 2, None, 4],
"B": ["one", "two", "three", None],"C": [False, None, False, True]})

In [158]:
df

     A      B      C
0  1.0    one  False
1  2.0    two   None
2  NaN  three  False
3  4.0    NaN   True

In [159]:
df["A"] = df["A"].astype("Int64")

In [160]:
df["B"] = df["B"].astype("string")

In [161]:
df["C"] = df["C"].astype("boolean")

In [162]:
df

      A      B      C
0     1    one  False
1     2    two   <NA>
2  <NA>  three  False
3     4   <NA>   True

## String Manipulation

**Python Built-In String Object Methods

In [163]:
val = "a,b, guido"

In [164]:
val.split(",")

['a', 'b', ' guido']

In [165]:
pieces = [x.strip() for x in val.split(",")]

In [166]:
pieces

['a', 'b', 'guido']

In [167]:
first , second , third = pieces

In [168]:
first + "::" + second + "::" + third

'a::b::guido'

In [169]:
# "::" = two colon delimiter

In [170]:
"::".join(pieces)  #second method to the same shi

'a::b::guido'

In [171]:
"guido" in val

True

In [172]:
val.index(",")

1

In [173]:
val.find(":")

-1

In [174]:
# find returns -1 but index returns error if the string is not founnd inthe dataframe

In [175]:
val.count(",")

2

In [176]:
val.replace(",","<<")

'a<<b<< guido'

In [177]:
val.replace(",","")

'ab guido'

**Regular expression

In [178]:
import re

In [179]:
text = "foo   bar\t baz  \tqux"

In [180]:
re.split(r"\s+", text )

['foo', 'bar', 'baz', 'qux']

In [181]:
regex = re.compile(r"\s+")

In [182]:
regex.split(text)

['foo', 'bar', 'baz', 'qux']

In [183]:
regex.findall(text)

['   ', '\t ', '  \t']

In [184]:
text = """Dave dave@google.com
Steve steve@gmail.com
Rob rob@gmail.com
Ryan ryan@yahoo.com"""
pattern = r"[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}"

In [185]:
regex = re.compile(pattern, flags = re.IGNORECASE)

In [186]:
regex.findall(text)

['dave@google.com', 'steve@gmail.com', 'rob@gmail.com', 'ryan@yahoo.com']

In [187]:
m = regex.search(text)

In [188]:
m

In [189]:
text[m.start():m.end()]

'dave@google.com'

In [190]:
print(regex.match(text))

None

In [191]:
print(regex.sub("REDATED", text))

Dave REDATED
Steve REDATED
Rob REDATED
Ryan REDATED

In [192]:
 pattern = r"([A-Z0-9._%+-]+)@([A-Z0-9.-]+)\.([A-Z]{2,4})"

In [193]:
regex =  re.compile(pattern, flags=re.IGNORECASE)

In [194]:
pattern

'([A-Z0-9._%+-]+)@([A-Z0-9.-]+)\\.([A-Z]{2,4})'

In [195]:
regex

re.compile(r'([A-Z0-9._%+-]+)@([A-Z0-9.-]+)\.([A-Z]{2,4})',
           re.IGNORECASE|re.UNICODE)

In [196]:
m = regex.match("wesm@bright.net")

In [197]:
m.groups()

('wesm', 'bright', 'net')

In [198]:
regex.findall(text)

[('dave', 'google', 'com'),
 ('steve', 'gmail', 'com'),
 ('rob', 'gmail', 'com'),
 ('ryan', 'yahoo', 'com')]

In [199]:
print(regex.sub(r"Username: \1, Domain: \2, Suffix: \3", text))

Dave Username: dave, Domain: google, Suffix: com
Steve Username: steve, Domain: gmail, Suffix: com
Rob Username: rob, Domain: gmail, Suffix: com
Ryan Username: ryan, Domain: yahoo, Suffix: com

**STRING FUNCTION IN PANDAS

In [200]:
data = {"Dave": "dave@google.com", "Steve": "steve@gmail.com",
.....:         
"Rob": "rob@gmail.com", "Wes": np.nan}

In [201]:
data = pd.Series(data)

In [202]:
data

Dave     dave@google.com
Steve    steve@gmail.com
Rob        rob@gmail.com
Wes                  NaN
dtype: str

In [203]:
data.isna()

Dave     False
Steve    False
Rob      False
Wes       True
dtype: bool

In [204]:
data.str.contains("gmail")

Dave     False
Steve     True
Rob       True
Wes      False
dtype: bool

In [205]:
data_as_strings_ext = data.astype('string')

In [206]:
data_as_strings_ext

Dave     dave@google.com
Steve    steve@gmail.com
Rob        rob@gmail.com
Wes                 <NA>
dtype: string

In [207]:
data_as_strings_ext.str.contains("gmail")

Dave     False
Steve     True
Rob       True
Wes       <NA>
dtype: boolean

In [208]:
pattern =  r"([A-Z0-9._%+-]+)@([A-Z0-9.-]+)\.([A-Z]{2,4})"

In [209]:
data.str.findall(pattern, flags=re.IGNORECASE)

Dave     [(dave, google, com)]
Steve    [(steve, gmail, com)]
Rob        [(rob, gmail, com)]
Wes                        NaN
dtype: object

In [210]:
matches = data.str.findall(pattern, flags=re.IGNORECASE).str[0]

In [211]:
matches

Dave     (dave, google, com)
Steve    (steve, gmail, com)
Rob        (rob, gmail, com)
Wes                      NaN
dtype: object

In [212]:
matches.str.get(1)

Dave     google
Steve     gmail
Rob       gmail
Wes         NaN
dtype: object

In [213]:
data.str[:5]

Dave     dave@
Steve    steve
Rob      rob@g
Wes        NaN
dtype: str

In [214]:
data.str.extract(pattern , flags = re.IGNORECASE)

           0       1    2
Dave    dave  google  com
Steve  steve   gmail  com
Rob      rob   gmail  com
Wes      NaN     NaN  NaN

In [215]:
data.str.contains("gmail")

Dave     False
Steve     True
Rob       True
Wes      False
dtype: bool

In [216]:
data.str.endswith('pat')

Dave     False
Steve    False
Rob      False
Wes      False
dtype: bool

In [217]:
data.str.count("gmail")

Dave     0.0
Steve    1.0
Rob      1.0
Wes      NaN
dtype: float64

## Categorical Data

In [218]:
values = pd.Series(['apple','orange','dingo','apple']*2)

In [219]:
values

0     apple
1    orange
2     dingo
3     apple
4     apple
5    orange
6     dingo
7     apple
dtype: str

In [220]:
values.unique()

<ArrowStringArray>
['apple', 'orange', 'dingo']
Length: 3, dtype: str

In [221]:
pd.unique(values)

<ArrowStringArray>
['apple', 'orange', 'dingo']
Length: 3, dtype: str

In [222]:
pd.Series(values).value_counts() #new version of value_counts for pandas

apple     4
orange    2
dingo     2
Name: count, dtype: int64

In [223]:
values.value_counts()

apple     4
orange    2
dingo     2
Name: count, dtype: int64

In [224]:
 values = pd.Series([0, 1, 0, 0] * 2)

In [225]:
values

0    0
1    1
2    0
3    0
4    0
5    1
6    0
7    0
dtype: int64

In [226]:
dim = pd.Series(['apple', 'orange'])

In [227]:
dim

0     apple
1    orange
dtype: str

In [228]:
dim.take(values)

0     apple
1    orange
0     apple
0     apple
0     apple
1    orange
0     apple
0     apple
dtype: str

In [229]:
 fruits = ['apple', 'orange', 'apple', 'apple'] * 2

In [230]:
N = len(fruits)

In [231]:
rng = np.random.default_rng(seed = 12345)

In [232]:
df = pd.DataFrame({'fruit':fruits, 'basket_id': np.arange(N), 'count': rng.integers(3,15,size=N), 'weight' : rng.uniform(0,4,size = N)},
                  columns = ['basket_id','fruit','count','weight'])

In [233]:
df

   basket_id   fruit  count    weight
0          0   apple     11  1.564438
1          1  orange      5  1.331256
2          2   apple     12  2.393235
3          3   apple      6  0.746937
4          4   apple      5  2.691024
5          5  orange     12  3.767211
6          6   apple     10  0.992983
7          7   apple     11  3.795525

In [234]:
# conversion of fruit array to categorical 
fruit_cat = df['fruit'].astype('category')

In [235]:
fruit_cat

0     apple
1    orange
2     apple
3     apple
4     apple
5    orange
6     apple
7     apple
Name: fruit, dtype: category
Categories (2, str): ['apple', 'orange']

In [236]:
fruit_cat.dtype

CategoricalDtype(categories=['apple', 'orange'], ordered=False, categories_dtype=str)

In [237]:
c = fruit_cat.array

In [238]:
c

['apple', 'orange', 'apple', 'apple', 'apple', 'orange', 'apple', 'apple']
Categories (2, str): ['apple', 'orange']

In [239]:
type(c)

pandas.Categorical

In [240]:
c.categories

Index(['apple', 'orange'], dtype='str')

In [241]:
c.codes

array([0, 1, 0, 0, 0, 1, 0, 0], dtype=int8)

In [242]:
dict(enumerate(c.categories))

{0: 'apple', 1: 'orange'}

In [243]:
df['fruit'] = df['fruit'].astype('category')

In [244]:
df['fruit']

0     apple
1    orange
2     apple
3     apple
4     apple
5    orange
6     apple
7     apple
Name: fruit, dtype: category
Categories (2, str): ['apple', 'orange']

In [245]:
# pandas.Categorical from other types of python sequences
my_categories = pd.Categorical(['foo','bar','baz','foo','bar'])

In [246]:
my_categories

['foo', 'bar', 'baz', 'foo', 'bar']
Categories (3, str): ['bar', 'baz', 'foo']

In [247]:
my_categories.dtype

CategoricalDtype(categories=['bar', 'baz', 'foo'], ordered=False, categories_dtype=str)

In [248]:
categories = ['foo', 'bar', 'baz']

In [249]:
codes = [0, 1, -1, 0, 0, 1]

In [250]:
categories

['foo', 'bar', 'baz']

In [251]:
my_cats_2 = pd.Categorical.from_codes(codes, categories)

In [252]:
my_cats_2

['foo', 'bar', NaN, 'foo', 'foo', 'bar']
Categories (3, str): ['foo', 'bar', 'baz']

In [253]:
dingo = ['chamar', 'bnsdk', 'lwdyum']

In [254]:
l = pd.Categorical.from_codes( codes,dingo)

In [255]:
l

['chamar', 'bnsdk', NaN, 'chamar', 'chamar', 'bnsdk']
Categories (3, str): ['chamar', 'bnsdk', 'lwdyum']

In [256]:
ordered_cat = pd.Categorical.from_codes(codes,categories, ordered = True)

In [257]:
ordered_cat

['foo', 'bar', NaN, 'foo', 'foo', 'bar']
Categories (3, str): ['foo' < 'bar' < 'baz']

In [258]:
#another method to make unordered categorical to ordered categorical is :
my_cats_2.as_ordered()

['foo', 'bar', NaN, 'foo', 'foo', 'bar']
Categories (3, str): ['foo' < 'bar' < 'baz']

In [259]:
rng = np.random.default_rng(seed = 12345)

In [260]:
draws = rng.standard_normal(1000)

In [261]:
draws[:5]

array([-1.42382504,  1.26372846, -0.87066174, -0.25917323, -0.07534331])

In [262]:
bins = pd.qcut(draws,4)

In [263]:
bins

[(-3.121, -0.675], (0.687, 3.211], (-3.121, -0.675], (-0.675, 0.0134], (-0.675, 0.0134], ..., (0.0134, 0.687], (0.0134, 0.687], (-0.675, 0.0134], (0.0134, 0.687], (-0.675, 0.0134]]
Length: 1000
Categories (4, interval[float64, right]): [(-3.121, -0.675] < (-0.675, 0.0134] < (0.0134, 0.687] < (0.687, 3.211]]

In [264]:
bins = pd.qcut(draws, 4 , labels = ['Q1','Q2','Q3','Q4'])

In [265]:
bins

['Q1', 'Q4', 'Q1', 'Q2', 'Q2', ..., 'Q3', 'Q3', 'Q2', 'Q3', 'Q2']
Length: 1000
Categories (4, str): ['Q1' < 'Q2' < 'Q3' < 'Q4']

In [266]:
bins.codes[:10]

array([0, 3, 0, 1, 1, 0, 0, 2, 2, 0], dtype=int8)

In [267]:
bins = pd.Series(bins, name = 'quartile')

In [268]:
bins

0      Q1
1      Q4
2      Q1
3      Q2
4      Q2
       ..
995    Q3
996    Q3
997    Q2
998    Q3
999    Q2
Name: quartile, Length: 1000, dtype: category
Categories (4, str): ['Q1' < 'Q2' < 'Q3' < 'Q4']

In [269]:
results = (pd.Series(draws).groupby(bins).agg(['count','min','max']).reset_index())

In [270]:
results

  quartile  count       min       max
0       Q1    250 -3.119609 -0.678494
1       Q2    250 -0.673305  0.008009
2       Q3    250  0.018753  0.686183
3       Q4    250  0.688282  3.211418

In [271]:
results['quartile']

0    Q1
1    Q2
2    Q3
3    Q4
Name: quartile, dtype: category
Categories (4, str): ['Q1' < 'Q2' < 'Q3' < 'Q4']

In [272]:
#this quartile contains the original categorical information

In [273]:
#better perfromance with categoricals

In [274]:
N = 10_000_000

In [275]:
labels = pd.Series(['foo','bar','baz','qux']*(N//4))  #(N//4) means divide and keep the absolute value that is the integer value not the floating value

In [276]:
categories = labels.astype('category')

In [277]:
labels.memory_usage(deep = True)

110000132

In [278]:
categories.memory_usage(deep = True)

10000177

In [279]:
%time _ = labels.astype('category')

CPU times: total: 297 ms
Wall time: 274 ms

In [280]:
%timeit labels.value_counts()

169 ms ± 3.84 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)

In [281]:
%timeit categories.value_counts()

37.3 ms ± 1.31 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)

In [282]:
s = pd.Series(['a', 'b', 'c', 'd'] * 2)

In [283]:
cat_s = s.astype('category')

In [284]:
cat_s

0    a
1    b
2    c
3    d
4    a
5    b
6    c
7    d
dtype: category
Categories (4, str): ['a', 'b', 'c', 'd']

In [285]:
cat_s.cat.codes  #Show the internal integer codes for each category

0    0
1    1
2    2
3    3
4    0
5    1
6    2
7    3
dtype: int8

In [286]:
 cat_s.cat.categories

Index(['a', 'b', 'c', 'd'], dtype='str')

In [287]:
#if the set of categories for this data extends beyond 4 then we use the following method

In [288]:
actual_categories = ['a', 'b', 'c', 'd', 'e']

In [289]:
actual_categories

['a', 'b', 'c', 'd', 'e']

In [290]:
cat_s2 = cat_s.cat.set_categories(actual_categories) #Replace / redefine the full list of allowed categories

In [291]:
cat_s2

0    a
1    b
2    c
3    d
4    a
5    b
6    c
7    d
dtype: category
Categories (5, str): ['a', 'b', 'c', 'd', 'e']

In [292]:
cat_s.value_counts()

a    2
b    2
c    2
d    2
Name: count, dtype: int64

In [293]:
cat_s2.value_counts()

a    2
b    2
c    2
d    2
e    0
Name: count, dtype: int64

In [294]:
 cat_s3 = cat_s[cat_s.isin(['a', 'b'])] #Keep only rows where value is "a" or "b"

In [295]:
cat_s3

0    a
1    b
4    a
5    b
dtype: category
Categories (4, str): ['a', 'b', 'c', 'd']

In [296]:
cat_s3.cat.remove_unused_categories()

0    a
1    b
4    a
5    b
dtype: category
Categories (2, str): ['a', 'b']

In [297]:
#this removed c and d here

In [298]:
cat_s = pd.Series(['a', 'b', 'c', 'd'] * 2, dtype='category')

In [300]:
pd.get_dummies(cat_s, dtype = 'boolean')

       a      b      c      d
0   True  False  False  False
1  False   True  False  False
2  False  False   True  False
3  False  False  False   True
4   True  False  False  False
5  False   True  False  False
6  False  False   True  False
7  False  False  False   True

In [ ]:
#this chapter hereby ends .....................